modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="aura" #mandatory

version="1.15.2-1.0.0" #mandatory

displayName="Astrum Aura" #mandatory

logoFile="examplemod.png" #optional

credits="Thanks for this example mod goes to everyone who helped developed this mod" #optional

authors="Howie" #optional

description='''
A space-themed mod that is inspired by Terraria's Calamity Mod's Astral Infection.
'''

[[dependencies.examplemod]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[36,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
